name: 'Issue Checker'
description: 'Checks issues'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
  issue-number:
    description: 'The number of the issue or pull request in which to create a comment.'
  comment-id:
    description: 'The id of the comment to update.'
  body:
    description: 'The comment body.'
runs:
  using: 'node12'
  main: 'index.js'